Add stub navigation for the project, profile and listings
sloik/HejtoBuzz pull request #18
Opened 2023-03-18 13:37 UTC by dominika-kokowicz

2023-03-18 18:02 UTC, sloik requested changes
Good job :)

2023-03-18 18:02 UTC, sloik commented on App/HejtoBuzz/HejtoBuzz/Views/Dashboard/ListingView.swift
> +//
Please remove the header comment :)

2023-03-18 18:02 UTC, sloik commented on App/HejtoBuzz/HejtoBuzz/Views/Dashboard/MainDashboardView.swift
> +//
Please remove the header comment :)

2023-03-18 18:02 UTC, sloik commented on App/HejtoBuzz/HejtoBuzz/Views/Dashboard/ProfileView.swift
> +//
Please remove the header comment :)

2023-03-18 18:02 UTC, sloik commented on App/HejtoBuzz/HejtoBuzz/Views/Theme.swift
> +//
Remove the comment ;)

2023-03-19 09:28 UTC, dominika-kokowicz commented on App/HejtoBuzz/HejtoBuzz.xcodeproj/project.pbxproj
> +				69F8C42E29C5F484002DD6A7 /* MainDashboardView.swift in Sources */,
Now yes - fixed :D

2023-03-19 09:28 UTC, dominika-kokowicz commented on App/HejtoBuzz/HejtoBuzz/Views/Dashboard/ListingView.swift
> +//
Fixed :)

2023-03-19 09:28 UTC, dominika-kokowicz commented on App/HejtoBuzz/HejtoBuzz/Views/Dashboard/MainDashboardView.swift
> +//
Fixed :)

2023-03-19 09:28 UTC, dominika-kokowicz commented on App/HejtoBuzz/HejtoBuzz/Views/Theme.swift
> +//
Fixed :)

2023-03-19 10:00 UTC, merged